### ISSUE TITLE
difficulties in reproducing this experiment

### ISSUE THREAD

**Issue by yoopaan** [joseilberto/top3next#1]
I notice there are data and mode files used in `main.py`：

```
    data_file = "data/kaggle_twitter.csv"
    model_file = "data/LSTM_model_local.pth"
    federated_file = "data/LSTM_model_federated.pth"
    dump_file = "data/pandas_df.pkl"
    word2idx_file = "data/tokenizer_keys.pkl"
```
Do these files need to be imported from outside?

Is it possible to reproduce the experiment？

**Comment by joseilberto** [comment]
@napoay The only external file to be downloaded is the kaggle_twitter.csv which is the dataset I discussed in the README file. 

Make sure you download it, rename it (if necessary) and place it in the folder data. 
The other 4 files are generated by the program.

**Comment by yoopaan** [comment]
@joseilberto 
Many thanks for your reply!

**Comment by yoopaan** [comment]
I found that the version of syft is very important. Can you tell me the exact version number used in this experiment?

**Comment by joseilberto** [comment]
I am not 100% sure, but I believe it was either 0.1.23 or 0.1.24. Both versions may be deprecated by now, which I would strongly encourage you to try the 0.3+. 

I also remember that syft required some small fixes to do the backward pass for LSTMs correctly. They may have it already implemented in new versions.

**Comment by yoopaan** [comment]
I tried to use syft 0.3.0, but I encountered many errors due to the upgrade of syft. When I change to syft 0.1.29, the LSTM model can generate:

<img width="411" alt="Screen Shot 2021-05-17 at 9 08 06 AM" src="https://user-images.githubusercontent.com/38783332/118419806-a82ea400-b6ef-11eb-856d-03ce23cc897f.png">

Then I encountered the following error:
```

Traceback (most recent call last):
  File "main.py", line 24, in <module>
    train_multiple_federated(model, remote_data, federated_file, len(word2idx))
  File "/Users/pan/Documents/top3next/federated.py", line 125, in train_multiple_federated
    validation_split)
  File "/Users/pan/Documents/top3next/federated.py", line 95, in train_federated
    verbose = False, topk_pred = 3)
  File "/Users/pan/Documents/top3next/utils/models.py", line 165, in fit
    outputs = self.forward(X_batch)
  File "/Users/pan/Documents/top3next/utils/models.py", line 66, in forward
    output, _ = self.bi_lstm(embedded, self.h_lstm)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/module.py", line 493, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 559, in forward
    return self.forward_tensor(input, hx)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 539, in forward_tensor
    output, hidden = self.forward_impl(input, hx, batch_sizes, max_batch_size, sorted_indices)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 519, in forward_impl
    self.check_forward_args(input, hx, batch_sizes)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 490, in check_forward_args
    self.check_input(input, batch_sizes)
  File "/usr/local/lib/python3.7/site-packages/torch/nn/modules/rnn.py", line 153, in check_input
    self.input_size, input.size(-1)))
RuntimeError: input.size(-1) must be equal to input_size. Expected 300, got 0

```
It should be related to the dimension of the word vector, but I don’t know how to modify it.

**Comment by joseilberto** [comment]
@napoay, I was not able to reproduce the error you are experiencing. What is the PyTorch version you are using? Maybe it is a problem with the dimensionality of the batches for the model.

**Comment by mh567** [comment]
@joseilberto I  used syft 0.1.23a and got the same error as  @napoay . My Pytorch version is 1.1, which is required by the requirement.txt of 0.1.23a.
And all installed packges is here:https://raw.githubusercontent.com/Vennyee/pip-list/main/pip-list

**Comment by joseilberto** [comment]
@zvatunb Sorry for the delayed response. I have been very busy with my thesis lately. I will check on it and give you some feedback this week. I am quite sure the syft version I used was the 0.1.23a with some updates from the community to support RNNs within the syft scope.

**Comment by pps121** [comment]
@joseilberto Please help how to get these files:

@napoay @zvatunb Please guide:

    data_file = "data/kaggle_twitter.csv"
    model_file = "data/LSTM_model_local.pth"
    federated_file = "data/LSTM_model_federated.pth"
    dump_file = "data/pandas_df.pkl"
    word2idx_file = "data/tokenizer_keys.pkl"
